# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Disctech
tagline:          'Discussing technology'
description:      'A simple blog regarding ASP.NET, Azure, Angular and other random stuffs'
url:              https://github.com/sdharshraj
baseurl:          /

author:
  name:           'Harsh Raj'
  url:            https://github.com/sdharshraj

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sdharshraj

gems: [jekyll-paginate, jekyll-gist]

social:
  twitter:        followharshraj
  
permalink:        /:year/:month/:title/

exclude: ["_app",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

kramdown:
  auto_ids: true
  
#PageList
pages_list:       
  About: '/about'
  Archive: '/archive'
#search
  collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major