# Permalinks
permalink:           pretty

# Setup
title:               Harsh Raj
tagline:             Discussing technology
url:                 https://github.com/sdharshraj/sdharshraj.github.io
paginate:            1
baseurl:             https://sdharshraj.github.io/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Harsh Raj
  url:               https://twitter.com/followharshraj
  email:             sdharshraj@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sdharshraj/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
#page list
  pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
