---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: Tech Talk
- type: text
  name: comments
  label: comments
  default: 'true'
- type: textarea
  default: description
  label: description
  name: description
- type: tag_list
  name: tags
  label: tags
pages:
- _posts/2018-04-29-sending-proactive-messaging-in-chatbot-using-microsoft-bot-framework.md
- _posts/2018-05-20-migrating-to-or-creating-new-qnamaker-with-microsoft-bot-framework.md
