---
pages:
- _posts/proactive-messaging-in-skype-for-business.md
- _posts/2018-04-29-sending-proactive-messaging-in-chatbot-using-microsoft-bot-framework.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: Tech Talk
- type: text
  name: comments
  label: comments
  default: 'true'
- type: textarea
  default: description
  label: description
  name: description
- type: text
  name: tags
  label: Tag
  config:
    required: true
